export const productsData = [
  {
    productId: 1,
    model: "dinosaur",
    name: "Khung Long - DIY Carton Build & Paint",
    shortName: "Khung Long",
    description: "Khoi goi tri to mo thoi tien su; hoc qua choi.",
    image: "/asset/sp1.jpg",
    images: ["/asset/sp1.jpg", "/asset/khunglong1.jpg", "/asset/khunglong2.png", "/asset/khunglong3.png"],
    price: 50000,
    stock: 80,
    tags: ["carton", "4-10", "steam"],
    concept: "Be tim hieu hinh khoi, luyen phoi mau va ke chuyen sang tao.",
    badges: ["Carton tai che", "Bo tron an toan", "Khong keo", "STEAM"],
    guideLink: "/huong-dan/khung-long",
    longDescription: ["Bo san pham gom nhieu manh ghep de dang lap rap."],
    specs: ["Chat lieu: Carton tai che", "Do tuoi: 4-10"],
    howTo: ["Tach cac manh theo ky hieu.", "Lap ghep theo thu tu."],
    safety: ["Nguoi lon ho tro tre nho."],
  },
  {
    productId: 2,
    model: "tank",
    name: "Xe Tang - DIY Carton Build & Paint",
    shortName: "Xe Tang",
    description: "Lam quen co cau than-thap-nong, luyen kien nhan.",
    image: "/asset/sp3.jpg",
    images: ["/asset/sp3.jpg", "/asset/xe1.png", "/asset/xe2.png", "/asset/xe3.png"],
    price: 50000,
    stock: 60,
    tags: ["carton", "4-10"],
    concept: "Lam quen lien ket hinh hoc qua mo hinh xe tang.",
    badges: ["Carton tai che", "Khong keo", "STEAM"],
    guideLink: "/huong-dan/xe-tang",
    longDescription: ["Than xe chac chan, phu hop cho be."],
    specs: ["Do tuoi: 4-10"],
    howTo: ["Lap khung gam truoc.", "Lap thap phao va nong."],
    safety: ["Khong dung len mo hinh."],
  },
  {
    productId: 3,
    model: "airplane",
    name: "May Bay - DIY Carton Build & Paint",
    shortName: "May Bay",
    description: "Kham pha canh-than-duoi, can doi hai ben.",
    image: "/asset/sp2.jpg",
    images: ["/asset/sp2.jpg", "/asset/mb1.png", "/asset/mb2.png", "/asset/mb3.png"],
    price: 50000,
    stock: 100,
    tags: ["carton", "4-10", "steam"],
    concept: "Kham pha cau truc may bay va tu do sang tao mau sac.",
    badges: ["Carton tai che", "Khong keo", "STEAM"],
    guideLink: "/huong-dan/may-bay",
    longDescription: ["Thiet ke canh rong, de lap rap."],
    specs: ["Do tuoi: 4-10"],
    howTo: ["Gap nep canh theo chi dan.", "Co dinh than-duoi."],
    safety: ["Khong nem manh vao nguoi vat."],
  },
];

